### ISSUE TITLE
Add User.getProfileLink()

### ISSUE THREAD

**Issue by FelixSFD** [Tunaki/chatexchange#5]
For SOBotics/Guttenberg#123, we need to get a link to a user's profile. As a workaround, we could build it by using the user-ID and `Room.getChatHost()` (which we had to map manually, because `ChatHost.getName()` is not public), but having `User.getProfileLink()` would be much cleaner.

### What exactly are we trying to achieve?

In [this line](https://github.com/SOBotics/Guttenberg/blob/eece78bbbc32c2737e53631b2a68f80952174098/src/main/java/org/sobotics/guttenberg/utils/PostUtils.java#L315), we need to send the link to the user's profile, who has posted the feedback to a plagiarism-report. In the current version of ChatExchange, we only get the strings `stack_overflow`, `stack_exchange` or `meta_stack_exchange` instead of the actual hostname. That's why we had to write [this](https://github.com/SOBotics/Guttenberg/blob/eece78bbbc32c2737e53631b2a68f80952174098/src/main/java/org/sobotics/guttenberg/utils/PostUtils.java#L331-L346) ugly workaround:

```
public static String getChatHostAsString(ChatHost host) {
	switch (host) {
		case STACK_OVERFLOW:
			return "stackoverflow.com";
		case STACK_EXCHANGE:
			return "stackexchange.com";
		case META_STACK_EXCHANGE:
			return "meta.stackexchange.com";
		default:
			return "stackoverflow.com"; 
	}
}
```

**Comment by Tunaki** [comment]
I actually don't see why `ChatHost.getName()` even exists now. What's more interesting than the name (which is already the name of the enum somewhat), is the URL to it, which is what Guttenberg is using. How about adding a `ChatHost.getBaseUrl()` that returns `https://chat.<...>.com`?

There isn't a real better way to get the profile link than building it. The `/user/info` route (useful because it take a list of user ids in batch, instead of making a single request for each user) sadly doesn't return it (example: `$.post('https://chat.stackoverflow.com/user/info',{roomId:111347,ids:6817005})`). As you suggest, I'll also add a method to retrieve the profile link directly.

**Comment by Tunaki** [comment]
Can you give a try to 1.1.2-SNAPSHOT and report back? (just pushed a new snapshot with this fix)

**Comment by FelixSFD** [comment]
Thank you! :-) It's working
